image-name: james-os
base-image: ghcr.io/ublue-os/bazzite:stable

modules:
  - type: bling
    install:
      - 1password

  - type: rpm-ostree
    install:
      - konsole     # terminal
      - piper       # Logitech-settings GUI
      - yakuake     # drop-down terminal